name: Setup Java Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Gradle wrapper
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle wrapper
        run: ./gradlew wrapper
